pull_request_rules:
  - name: label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependencies]
  - name: automatically merge scala-steward's patch PRs
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, adopt@1.11)
    actions:
      merge:
        method: merge