version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data_${THOMAS_ENV}:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - kafka_data_${THOMAS_ENV}:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper

  mongo:
    container_name: thomas-mongodb-${THOMAS_ENV}
    image: 'mongo:4.2.11'
    ports:
      - ${THOMAS_MONGO_PORT}:27017
    volumes:
      - mongo_data_${THOMAS_ENV}:/data/db

  dynamo:
    container_name: thomas-dynamo-${THOMAS_ENV}
    build:
      context: .
      dockerfile: docker/dynamodb/Dockerfile
    ports:
      - ${THOMAS_DYNAMO_PORT}:8000
    volumes:
      - dynamo_data_${THOMAS_ENV}:/home/dynamodblocal/db


volumes:
  zookeeper_data_test:
  kafka_data_test:
  zookeeper_data_dev:
  kafka_data_dev:
  mongo_data_test:
  dynamo_data_test:
  mongo_data_dev:
  dynamo_data_dev:
