version: '2'

services:
  kafka:
    image: apache/kafka:4.2.0
    ports:
      - '9092:9092'
    volumes:
      - kafka_data_${THOMAS_ENV}:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    container_name: thomas-mongodb-${THOMAS_ENV}
    image: 'mongo:6.0.13'
    ports:
      - ${THOMAS_MONGO_PORT}:27017
    volumes:
      - mongo_data_${THOMAS_ENV}:/data/db

  dynamo:
    container_name: thomas-dynamo-${THOMAS_ENV}
    build:
      context: .
      dockerfile: docker/dynamodb/Dockerfile
    ports:
      - ${THOMAS_DYNAMO_PORT}:8000
    volumes:
      - dynamo_data_${THOMAS_ENV}:/home/dynamodblocal/db


volumes:
  kafka_data_test:
  kafka_data_dev:
  mongo_data_test:
  dynamo_data_test:
  mongo_data_dev:
  dynamo_data_dev:
