name: Continuous Integration

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['master']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  THOMAS_ADMIN_KEY: "ecf9b0704e8bfc153a99d9e269c4fdfba54f9d9297881a99317d907a29c8cabccb9c23a4ab0f9dc70663cf74f11f257914e95e99e7b0e3a5f16f321269a239c5be7dd46c03e4f78f80f161e138723ceff4a00e893dc712f9b23881e3c7c00f7367a1d7b36fba5d92640979029bdf6fdbf48b740771613edaba9d73d42146b8ee2638e08fecb1c78ce3a216f4493024ff444a4f9fe8c2f5ca21edd5f4c775205fecacce1eaaaa0bdd84704944816b19d0d2061a4841e4e6939a7ab9b931ccf314332ac00d4bf249ccdbb12f4467aad01405d4b37e187507678334f596678f415e6395d8a4df9498c862b37342f03f52ff7d0425d6f40b649fa3f19fe13cb65183"

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.15]
        java: [adopt@1.11]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Validation
        run: sbt validate

